// SPDX-FileCopyrightText: 2026 ArcheBase
//
// SPDX-License-Identifier: MulanPSL-2.0

#ifndef AXON_RECORDER_VERSION_HPP
#define AXON_RECORDER_VERSION_HPP

/**
 * Auto-generated version header from CMake project version
 * Do not edit manually - regenerated by CMake
 */

// C-style macros (with _MACRO suffix to avoid conflicts)
#define AXON_RECORDER_VERSION_MACRO "0.2.1"
#define AXON_RECORDER_VERSION_MAJOR_MACRO 0
#define AXON_RECORDER_VERSION_MINOR_MACRO 2
#define AXON_RECORDER_VERSION_PATCH_MACRO 1

// C++ namespace with constexpr variables
namespace axon {
namespace recorder {

constexpr const char* AXON_RECORDER_VERSION_STRING = "0.2.1";
constexpr int AXON_RECORDER_VERSION_MAJOR = 0;
constexpr int AXON_RECORDER_VERSION_MINOR = 2;
constexpr int AXON_RECORDER_VERSION_PATCH = 1;

// Convenience alias for use in code
constexpr const char* AXON_RECORDER_VERSION = AXON_RECORDER_VERSION_STRING;

// Helper functions to get version information
inline const char* get_version() {
  return AXON_RECORDER_VERSION_STRING;
}

inline const char* get_version_info() {
  static constexpr char version_info[] =
    "Axon Recorder 0.2.1\n"
    "Copyright (c) 2026 ArcheBase\n"
    "Licensed under Mulan PSL v2\n"
    "\n"
    "MCAP-based ROS message recorder with HTTP RPC API\n"
    "Plugin architecture: ROS1/ROS2 support\n"
    "Website: https://github.com/ArcheBase/Axon";
  return version_info;
}

}  // namespace recorder
}  // namespace axon

#endif  // AXON_RECORDER_VERSION_HPP
