name: Bug Report
description: Report a problem or bug in Axon
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in Axon! Please fill out the information below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: |
        What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: |
        The recorder should finish cleanly and save the MCAP file.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: |
        The recorder crashed with a segmentation fault in worker_thread_pool.cpp:142
    validations:
      required: true

  - type: input
    id: axon-version
    attributes:
      label: Axon Version
      description: The version of Axon you are using
      placeholder: "v0.2.0"
    validations:
      required: true

  - type: dropdown
    id: ros-distro
    attributes:
      label: ROS Distribution
      description: Which ROS distribution are you using?
      options:
        - ROS 1 Noetic
        - ROS 2 Humble
        - ROS 2 Jazzy
        - ROS 2 Rolling
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your operating system and version
      placeholder: "Ubuntu 22.04 LTS"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output or error messages
      render: shell
      placeholder: |
        [ERROR] [1638360000.123] [axon_recorder]: Failed to write message to MCAP
        terminate called after throwing an instance of 'std::runtime_error'
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: If applicable, paste your configuration (remove sensitive info)
      render: yaml
      placeholder: |
        task_config:
          task_id: "task_123"
          device_id: "robot_01"
          topics: ["/camera/image", "/lidar/scan"]
    validations:
      required: false

  - type: textarea
    id: minimal-reproduction
    attributes:
      label: Minimal Reproduction
      description: If possible, provide a minimal code example or repository that reproduces the bug
      render: shell
      placeholder: |
        ```bash
        # Minimal reproduction script
        #!/bin/bash
        source /opt/ros/humble/setup.bash
        ./axon_recorder --config test_config.yaml
        ```
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about the bug
      placeholder: |
        - This issue occurs consistently after pausing and resuming recording
        - Does not occur when recording without pause/resume
        - Works fine on ROS2 Humble but fails on Jazzy
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please complete the following steps
      options:
        - label: I have searched existing issues for similar bugs
          required: true
        - label: I have checked the [README](https://github.com/ArcheBase/Axon/blob/main/README.md) and [ARCHITECTURE](https://github.com/ArcheBase/Axon/blob/main/ARCHITECTURE.md) documentation
          required: false
        - label: I have verified the bug still occurs in the latest version
          required: false
