/*
 * Axon Lance Bridge - C FFI Interface
 * Auto-generated by cbindgen. Do not edit directly.
 *
 * This header provides the C interface to the Axon Lance writer,
 * which writes ROS data to Lance format for efficient storage and querying.
 *
 * https://github.com/archebase/axon
 */

/* Non-null pointer hint (used by static analyzers) */
#ifndef AXON_NONNULL
#define AXON_NONNULL
#endif

/* Arrow FFI types (Arrow C Data Interface) */
struct ArrowSchema;
struct ArrowArray;

/* Type aliases matching Rust arrow::ffi naming */
typedef struct ArrowSchema FFI_ArrowSchema;
typedef struct ArrowArray FFI_ArrowArray;


#ifndef AXON_LANCE_BRIDGE_H
#define AXON_LANCE_BRIDGE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "stdint.h"

/**
 * Operation completed successfully
 */
#define AXON_LANCE_SUCCESS 0

/**
 * Invalid path provided
 */
#define AXON_LANCE_ERROR_INVALID_PATH -1

/**
 * Invalid schema provided
 */
#define AXON_LANCE_ERROR_INVALID_SCHEMA -2

/**
 * Dataset operation error
 */
#define AXON_LANCE_ERROR_DATASET -3

/**
 * Arrow conversion error
 */
#define AXON_LANCE_ERROR_ARROW -4

/**
 * IO error
 */
#define AXON_LANCE_ERROR_IO -5

/**
 * Invalid dataset handle
 */
#define AXON_LANCE_ERROR_INVALID_HANDLE -6

#define LANCE_SUCCESS AXON_LANCE_SUCCESS

#define LANCE_ERROR_INVALID_PATH AXON_LANCE_ERROR_INVALID_PATH

#define LANCE_ERROR_INVALID_SCHEMA AXON_LANCE_ERROR_INVALID_SCHEMA

#define LANCE_ERROR_DATASET AXON_LANCE_ERROR_DATASET

#define LANCE_ERROR_ARROW AXON_LANCE_ERROR_ARROW

#define LANCE_ERROR_IO AXON_LANCE_ERROR_IO

#define LANCE_ERROR_INVALID_HANDLE AXON_LANCE_ERROR_INVALID_HANDLE

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Get the last error message as a C string
 *
 * Returns a pointer to the error message string, or NULL if no error.
 * The returned string is valid until the next error occurs on this thread.
 *
 * # Safety
 * The returned pointer is valid until the next call to any Axon function
 * that may set an error on this thread.
 */
const char *axon_lance_get_last_error(void);

/**
 * Legacy name for backward compatibility
 */
const char *lance_get_last_error(void);

/**
 * Create or open a Lance dataset
 *
 * Opens an existing dataset at the given path, or creates a new one if it doesn't exist.
 *
 * # Arguments
 * * `path` - Path to the dataset (null-terminated C string)
 * * `schema_ptr` - Pointer to Arrow schema (FFI_ArrowSchema from Arrow C Data Interface)
 *
 * # Returns
 * * Positive handle (i64) on success - use this handle for subsequent operations
 * * 0 on error - call `axon_lance_get_last_error()` for details
 *
 * # Safety
 * * `path` must be a valid null-terminated C string
 * * `schema_ptr` must be a valid pointer to an FFI_ArrowSchema
 */
int64_t axon_lance_create_dataset(const char *path, FFI_ArrowSchema *schema_ptr);

/**
 * Write a RecordBatch to a Lance dataset
 *
 * Appends data to the dataset. The data is passed via Apache Arrow's C Data Interface
 * for zero-copy transfer.
 *
 * # Arguments
 * * `dataset_handle` - Handle returned by `axon_lance_create_dataset`
 * * `array_ptr` - Pointer to Arrow array (FFI_ArrowArray - StructArray representing RecordBatch)
 * * `schema_ptr` - Pointer to Arrow schema (FFI_ArrowSchema)
 *
 * # Returns
 * * `AXON_LANCE_SUCCESS` (0) on success
 * * Negative error code on failure - call `axon_lance_get_last_error()` for details
 *
 * # Safety
 * * `dataset_handle` must be a valid handle from `axon_lance_create_dataset`
 * * `array_ptr` must be a valid pointer to an FFI_ArrowArray
 * * `schema_ptr` must be a valid pointer to an FFI_ArrowSchema
 */
int axon_lance_write_batch(int64_t dataset_handle,
                           FFI_ArrowArray *array_ptr,
                           FFI_ArrowSchema *schema_ptr);

/**
 * Close a dataset and release resources
 *
 * Closes the dataset and frees all associated resources.
 * The handle becomes invalid after this call.
 *
 * # Arguments
 * * `dataset_handle` - Handle returned by `axon_lance_create_dataset`
 *
 * # Returns
 * * `AXON_LANCE_SUCCESS` (0) on success
 * * Negative error code on failure
 */
int axon_lance_close_dataset(int64_t dataset_handle);

/**
 * Legacy: Create or open a Lance dataset
 * Use `axon_lance_create_dataset` instead.
 */
int64_t create_or_open_dataset(const char *path, FFI_ArrowSchema *schema_ptr);

/**
 * Legacy: Write a RecordBatch to a Lance dataset
 * Use `axon_lance_write_batch` instead.
 */
int write_batch(int64_t dataset_handle, FFI_ArrowArray *array_ptr, FFI_ArrowSchema *schema_ptr);

/**
 * Legacy: Close a dataset
 * Use `axon_lance_close_dataset` instead.
 */
int close_dataset(int64_t dataset_handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AXON_LANCE_BRIDGE_H */
